server:
  port: 8877
spring:
  activemq:
    broker-url: mqtt://127.0.0.1:1883
    user: admin
    password: admin
  jms:
    pub-sub-domain: false # false = queue true = topic

myqueue: boot-activemq-queue
